### ISSUE TITLE
Can't change pinged IP address

### ISSUE THREAD

**Issue by dantearmok** [yonkavalow/PingStatus#1]
in Sierra, PingStatus's preferences look normal, and I can type in an IP address.  But when I close and re-open the prefs, the IP is reverted to what it was originally.

**Comment by yonkavalow** [comment]
try hitting enter/return after changing the ip. there could be a bug where the Close button is not saving the setting.

**Comment by dantearmok** [comment]
Yup!  Hitting return worked!  Thanks!

- Dan.

**Comment by yonkavalow** [comment]
Dan- version 1.7.18 fixes this bug.
Thanks
