### ISSUE TITLE
Donno how many ms

### ISSUE THREAD

**Issue by dantearmok** [yonkavalow/PingStatus#2]
In the preferences, Average Delay says "ms" but no number.  Notifications are also devoid of the number.

**Comment by yonkavalow** [comment]
Dan- please update and see if this issue is addressed.
Thanks

**Comment by dantearmok** [comment]
Updated; the problem continues.

Steps to reproduce:
0. Open prefs.
1. Change target host to one that doesn’t exist.
2. Wait for the average delay to decrease to just “ms”.



HTH,
- Dan.

**Comment by yonkavalow** [comment]
Is ‘Last Delay’ showing a value for ms after you change the target host?

-Jon

**Comment by dantearmok** [comment]
Last Delay says “Timeout” initially.
